config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "spaceships#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :spaceships do
    resources :bookings, only: [:new, :create, :show]
  end
  resources :bookings, only: [:edit, :update, :destroy]
  get "/profile", to: "pages#profile", as: :profile
  get "/bookings", to: "pages#booking", as: :bookings

  get "/bookings/:id/accept", to: "bookings#accept", as: :accept_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :spaceship
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord

  include PgSearch::Model

  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_many_attached :photos

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  pg_search_scope :search_by_name_location_and_category,
    against: [:name, :location, :category],
    using: {
      tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :spaceships
  has_many :received_bookings, through: :spaceships, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @spaceship = Spaceship.find(params[:spaceship_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.total = calc_total
    @spaceship = Spaceship.find(params[:spaceship_id])
    @booking.spaceship = @spaceship
    @booking.user = current_user
    if @booking.save
      redirect_to spaceships_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: true)
    redirect_to bookings_path
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.spaceship.user == current_user
      @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def calc_total
    @spaceship = Spaceship.find(params[:spaceship_id])
    @start_date = Date.strptime(params[:booking][:start_date], '%Y-%m-%d')
    @end_date = Date.strptime(params[:booking][:end_date], '%Y-%m-%d')
    @days = @end_date - @start_date
    total = @spaceship.price * @days
    return total
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
    if current_user.nil?
      redirect_to spaceships_path
    else
      @spaceships = current_user.spaceships
    end
  end

  def booking
    @my_spaceships = current_user.spaceships.joins(:bookings)
    @my_bookings = current_user.bookings.joins(:spaceship)
    if current_user.nil?
      redirect_to spaceships_path
    else
      @bookings = current_user.bookings
    end
  end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  def index
    @spaceships = Spaceship.all
    if params[:query].present?
      @spaceships = Spaceship.search_by_name_location_and_category(params[:query])
    else
      @spaceships = Spaceship.all
    end
  end

  def show
    @spaceship = Spaceship.find(params[:id])

    @markers = [
      {
        lat:@spaceship.latitude,
        lng: @spaceship.longitude,
        marker_html: render_to_string(partial: "marker")
    }]
    @booking = Booking.new
  end

  def new
    @spaceship = Spaceship.new
  end

  def create
    @spaceship = Spaceship.new(spaceship_params)
    @spaceship.user = current_user
    if @spaceship.save
      redirect_to spaceship_path(@spaceship)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @spaceship = Spaceship.find(params[:id])
  end

  def update
    @spaceship = Spaceship.find(params[:id])
    @spaceship.update(spaceship_params)
    redirect_to spaceship_path(@spaceship)
  end

  def destroy
    @spaceship = Spaceship.find(params[:id])
    if current_user == @spaceship.user
      @spaceship.destroy
      redirect_to profile_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def spaceship_params
    params.require(:spaceship).permit(:name, :category, :location, :price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container mt-4" style="width: 400px">
  <h1>Accept booking for <%= @booking.spaceship.name %> </h1>
                    <%# PARENT, CHILD %>
  <div class="container"><div class="d-flex justify-content-between">
                  <h3 class="d-flex align-items-center ms-3">
                    <i class="fa-solid fa-calendar-check fs-2"></i>
                    <p class="ms-2 fs-5 mt-2"><%= @booking.start_date %></p>
                  </h3>
                  <h3 class="d-flex align-items-center ms-0 mt-2 me-3">
                    <i class="fa-solid fa-calendar-xmark fs-2"></i>
                    <p class="ms-2 fs-5 mt-1"><%= @booking.end_date %></p>
                  </h3>
                </div></div>

  <div class="form-inputs">
    <%= simple_form_for [@booking], data: { controller: 'flatpickr' } do |f| %>
        <% f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
        <% f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
      <div class="d-flex justify-content-between mt-4">
        <%= f.input :status, as: :select, collection: ["Accept Booking"], prompt: 'Decision' %>
        <%= f.button :submit, class: 'btn btn-gradient' %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container mt-4" style="width: 400px">
  <h1>Add a Booking to the <%= @spaceship.name %> Spaceship</h1>
                    <%# PARENT, CHILD %>
  <div class="form-inputs">
    <%= simple_form_for [@spaceship, @booking], data: { controller: 'flatpickr' } do |f| %>
        <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
        <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
      <div class="d-flex justify-content-between align-items-center mt-4">
        <div>
          <%= link_to "Cancel", spaceship_path(@spaceship), class: "btn btn-danger"%>
        </div>
        <%#= f.button :submit, class: 'btn btn-gradient' %>
        <div>
          <%= render "shared/rocket_button" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AstroRide</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/banner" %>
    <div style="min-height: 70vh;">
     <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/booking.html.erb
<div class="container">
  <h1 class="mb-4">My Rented Spaceships</h1>

  <% if @my_spaceships.empty? %>
    <p class="fs-5"><i>You don't have any bookings yet!</i></p>
  <% else %>
    <% used_spaceships = [] %>
    <div class="row">
      <% @my_spaceships.each do |spaceship| %>
        <% if !used_spaceships.include?(spaceship) %>
          <div class="col-md-4">
            <div class="card-spaceship mb-5">
              <% if spaceship.photos.attached? %>
                <%= cl_image_tag(spaceship.photos[0].key) %>
              <% else %>
                <img src="https://source.unsplash.com/random/?rocket">
              <% end %>
              <div class="card-spaceship-infos">
                <%= render spaceship %>
                <h3 class="card-spaceship-category">
                  <%= spaceship.category %>
                </h3>
              </div>
              <% spaceship.bookings.each do |booking| %>
                <div class="container mt-2 border-top">
                  <div class="d-flex justify-content-between">
                    <h3 class="d-flex align-items-center ms-3">
                      <i class="fa-solid fa-calendar-check fs-2"></i>
                      <p class="ms-2 fs-5 mt-2"><%= booking.start_date %></p>
                    </h3>
                    <h3 class="d-flex align-items-center ms-0 mt-2 me-3">
                      <i class="fa-solid fa-calendar-xmark fs-2"></i>
                      <p class="ms-2 fs-5 mt-1"><%= booking.end_date %></p>
                    </h3>
                  </div>

                  <h3 class="d-flex align-items-center mt-3 fs-3">
                    Total:
                    <p class="ms-2 fs-5 mt-1">$ <%= booking.total.to_i %></p>
                  </h3>
                </div>
                <br>
                <div class="mb-3">
                  <h3>
                    <% if booking.status == nil %>
                      <h3 class="d-flex justify-content-center fs-5 text-success">
                        Accept Booking?
                      </h3>
                      <div class="d-flex justify-content-center m-3 mt-4">
                        <div>
                          <%= link_to accept_booking_path(booking), class: "text-success me-4" do %>
                            <%= content_tag(:i, "", class: "fa-solid fa-circle-check fs-1") %>
                          <% end %>
                        </div>
                        <div>
                          <%= link_to booking_path(booking), data: { turbo_method: 'DELETE', turbo_confirm: "Reject #{booking.spaceship.name} Booking?" }, class: "ms-4", style:"color: lightgrey" do %>
                            <%= content_tag(:i, "", class: "fa-solid fa-circle-xmark fs-1") %>
                          <% end %>
                        </div>
                      </div>
                    <% else %>
                      <h3 class="d-flex justify-content-center text-success fs-5">
                        <i class="fa-solid fa-circle-check me-2"></i> Booking Accepted!
                      </h3>
                      <div class="d-flex justify-content-end me-3">
                        <%= link_to booking_path(booking), data: { turbo_method: 'DELETE', turbo_confirm: "You will be charged for #{booking.total}$ \n Cancel #{booking.spaceship.name} booking anyway?" }, class: "btn btn-del mt-3" do %>
                          <%= content_tag(:i, "", class: "fa-solid fa-trash-can fs-4", style:"color: #ffffff;") %>
                        <% end %>
                      </div>
                    <% end %>
                  </h3>
                </div>
              <% end %>
            </div>
            <% used_spaceships << spaceship %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="container">
  <h1 class=" mb-4">My Bookings</h1>
  <% if @my_bookings.empty? %>
    <p class="fs-5"><em>You don't have any Booking yet! </em></p>
  <% else %>
    <div class="row">
      <% @my_bookings.each do |booking| %>
        <div class="col-md-4">
          <div class="card-spaceship mb-5">
            <% if booking.spaceship.photos.attached? %>
              <%= cl_image_tag(booking.spaceship.photos[0].key) %>
            <% else %>
              <img src="https://source.unsplash.com/random/?rocket">
            <% end %>

            <div class="card-spaceship-infos">
              <div id="<%= dom_id booking.spaceship%>">
<h2 class="mb-1"><%= booking.spaceship.name %></h2>
  <p>
    <i class="fa-solid fa-location-dot"></i>
    <%= booking.spaceship.location.split(',')[-1] %>
  </p>
  <h3>
    <i class="fa-solid fa-dollar-sign"></i>
    <%= booking.spaceship.price.to_i %>
    <span style="color: grey">per day</span>
  </h3>
</div>
<h3 class="card-spaceship-category">
                  <%= booking.spaceship.category %>
                </h3>
            </div>
            <div class="container mt-2 border-top">
              <div class="d-flex justify-content-between">
                <h3 class="d-flex align-items-center ms-3">
                  <i class="fa-solid fa-calendar-check fs-2"></i>
                  <p class="ms-2 fs-5 mt-2"><%= booking.start_date %></p>
                </h3>
                <h3 class="d-flex align-items-center ms-0 mt-2 me-3">
                  <i class="fa-solid fa-calendar-xmark fs-2"></i>
                  <p class="ms-2 fs-5 mt-1"><%= booking.end_date %></p>
                </h3>
              </div>

              <h3 class="d-flex align-items-center mt-3">
              Total:
                <p class="ms-2 fs-5 mt-1">$ <%= booking.total.to_i%></p>
              </h3>
            </div>

              <br>

            <div class="d-flex justify-content-center mb-3">
              <h3>
                <% if booking.status == nil %>
                  <h3 class="text-muted fs-5"><i class="fa-solid fa-spinner"></i></i> Booking pending</h3>
                <% else %>
                  <h3 class="text-success fs-5"><i class="fa-solid fa-circle-check"></i></i> Booking Accepted!</h3>
                <% end %>
              </h3>
            </div>
            <div class="d-flex justify-content-end m-3">
              <div>
                <%= link_to booking_path(booking),
                    data: { turbo_method: 'DELETE',
                    turbo_confirm: "Delete #{booking.spaceship.name} Spaceship Booking?" },
                    class: "btn btn-del" do %>
                    <%= content_tag(:i, "", class: "fa-solid fa-trash-alt", style:"color: #ffffff;") %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/profile.html.erb
<div class="container mb-2 mt-5">
  <div class="col-md-12">
    <h1>My Spaceships</h1>
    <% if @spaceships.empty? %>
      <p class="fs-5 mt-5 mb-2">
        <i>You do not have any spaceships yet! </i>
        <i class="fa-brands fa-rocketchat"></i>
      </p>
      <br>
      <%= link_to "Rent out your first spaceship!", new_spaceship_path, class: "btn btn-success mb-5" %>
    <% else %>
      <% @spaceships.each do |spaceship| %>
        <div class="card-my-spaceships mb-5 mt-5">
          <% if spaceship.photos.attached? %>
            <%= cl_image_tag(spaceship.photos[0].key) %>
          <% else %>
            <img src="https://source.unsplash.com/random/?rocket">
          <% end %>

          <div class="card-my-spaceships-content">
              <h2><%= spaceship.name %></h2>
            <h3>
                <i class="fa-solid fa-dollar-sign"></i>
                <%= spaceship.price %>
                <span style="color: grey">per day</span>
              </h3>
            <p>
                <i class="fa-solid fa-location-dot"></i>
                <%= spaceship.location %>
              </p>
            <p class="card-my-spaceships-category"><%= spaceship.category %></p>

            <div class="button-group">
              <%= link_to edit_spaceship_path(spaceship), class: "btn btn-success" do %>
                <%= content_tag(:i, "", class: "fa-solid fa-pencil-alt") %>
              <% end %>

              <%= link_to spaceship_path(spaceship), method: :delete, data: { turbo_method: 'DELETE', turbo_confirm: "Delete #{spaceship.name} Spaceship?" }, class: "btn btn-del", style:"color:white;" do %>
                <%= content_tag(:i, "", class: "fa-solid fa-trash-alt") %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(179deg, rgb(0 0 0),rgb(0 0 0 / 0%), #000000c4)
, url(https://spaceflightnow.com/wp-content/uploads/2022/08/20220831starlink34.jpg);">
  <div class="container" style="font-famiy: Orbitron">
    <h1>AstroRide</h1>
    <p style="font-family: Orbitron;" data-controller="typed"></p>
  </div>
</div>

app/views/shared/_button_create.html.erb
<button type="submit" class="button-upload" routerLink="/spaceships">
	<span class="button-upload__text">Create</span>
  <svg
		xmlns="http://www.w3.org/2000/svg"
		width="40.089"
		height="34.388"
		class="button-upload__logo"
		viewBox="0 0 36.089 34.388"
	>
		<g
			transform="translate(26.150) rotate(49)"
			class="button-upload__logo--complete"
		>
			<g
				transform="translate(5.976 28.664)"
				class="button-upload__logo--trails"
			>
				<path
					d="M153.97,738.46l1.692.055v6.115l-1.692-1.147"
					transform="translate(-153.97 -738.46)"
					fill="#fafafa"
				/>
				<path
					d="M337.1,738.46l-1.692.055v6.115l1.692-1.147"
					transform="translate(-328.367 -738.46)"
					fill="#fafafa"
				/>
				<path
					d="M243.98,738.46h1.692V747l-.846.939-.846-.971"
					transform="translate(-240.486 -738.46)"
					fill="#fafafa"
				/>
			</g>
			<g class="button-upload__logo--rocket">
				<path
					d="M19.627,21.9l-2.95-2.95A28.11,28.11,0,0,0,10.3,0,28.1,28.1,0,0,0,3.923,18.952L.973,21.9s-1.454,4.092-.8,6.822l4.393-4.378q.074.358.155.721H5.7l.981.979h3.606l.017-.979.017.979h3.605l.979-.979h.979q.083-.363.155-.721l4.393,4.378C21.082,25.994,19.627,21.9,19.627,21.9Zm-9.3-2.65a2.7,2.7,0,1,1,2.7-2.7A2.7,2.7,0,0,1,10.323,19.252Z"
					transform="translate(-0.002 0)"
					fill="#fafafa"
				/>
			</g>
		</g>
	</svg>
</button>

app/views/shared/_button_upload.html.erb
<button type="submit" class="button-upload" routerLink="/spaceships/id/edit">
	<span class="button-upload__text">Update</span>
  <svg
		xmlns="http://www.w3.org/2000/svg"
		width="40.089"
		height="34.388"
		class="button-upload__logo"
		viewBox="0 0 36.089 34.388"
	>
		<g
			transform="translate(26.150) rotate(49)"
			class="button-upload__logo--complete"
		>
			<g
				transform="translate(5.976 28.664)"
				class="button-upload__logo--trails"
			>
				<path
					d="M153.97,738.46l1.692.055v6.115l-1.692-1.147"
					transform="translate(-153.97 -738.46)"
					fill="#fafafa"
				/>
				<path
					d="M337.1,738.46l-1.692.055v6.115l1.692-1.147"
					transform="translate(-328.367 -738.46)"
					fill="#fafafa"
				/>
				<path
					d="M243.98,738.46h1.692V747l-.846.939-.846-.971"
					transform="translate(-240.486 -738.46)"
					fill="#fafafa"
				/>
			</g>
			<g class="button-upload__logo--rocket">
				<path
					d="M19.627,21.9l-2.95-2.95A28.11,28.11,0,0,0,10.3,0,28.1,28.1,0,0,0,3.923,18.952L.973,21.9s-1.454,4.092-.8,6.822l4.393-4.378q.074.358.155.721H5.7l.981.979h3.606l.017-.979.017.979h3.605l.979-.979h.979q.083-.363.155-.721l4.393,4.378C21.082,25.994,19.627,21.9,19.627,21.9Zm-9.3-2.65a2.7,2.7,0,1,1,2.7-2.7A2.7,2.7,0,0,1,10.323,19.252Z"
					transform="translate(-0.002 0)"
					fill="#fafafa"
				/>
			</g>
		</g>
	</svg>
</button>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to(root_path, class: "navbar-brand") do %>
          <i class="fa-solid fa-rocket fs-1" style="color: #ffffff; margin-left: 25px;"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
     <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-lg-6">
            <%= form_tag(spaceships_path, method: :get, class: "simple_form search") do %>
              <div class="search-form-control form-group">
                <%= text_field_tag(:query, params[:query], class: "form-control", placeholder: 'Search spaceships...') %>
                <button class="btn btn-flat" type="submit">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-solid fa-user-astronaut fs-1", style="color: white; margin-right: 25px"></i>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
  <div>
    <%= link_to "<i class='fas fa-home'></i> Home".html_safe, spaceships_path, class: "dropdown-item" %>
  </div>
  <div class="d-flex">
    <%= link_to "<i class='fas fa-rocket'></i> Rent out Spaceship".html_safe, new_spaceship_path, class: "dropdown-item" %>
  </div>
  <div>
    <%= link_to "<i class='fa-solid fa-folder'></i> My Spaceships".html_safe, profile_path, class: "dropdown-item" %>
  </div>
  <div>
    <%= link_to "<i class='fas fa-calendar'></i> My Bookings".html_safe, bookings_path, class: "dropdown-item" %>
  </div>
  <div>
    <%= link_to "<i class='fas fa-sign-out-alt'></i> Log out".html_safe, destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
  </div>
</div>

          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/spaceships/show.html.erb
<div class="container mt-4">
          <h1><%= @spaceship.name %></h1>

  <div class="row">
    <div class="col-md-7 ">
      <div class="card-show mb-5">
        <% if @spaceship.photos.attached? %>
          <div class="d-flex align-items-center justify-content-center">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active" style="height: 400px; object-fit: cover;">
                  <%= cl_image_tag(@spaceship.photos[0].key, class:"d-block w-100") %>
                </div>
                <% @spaceship.photos.drop(1).each do |photo| %>
                  <div class="carousel-item" style="height: 400px; object-fit: cover;">
                    <%= cl_image_tag(photo.key, class:"d-block w-100") %>
                  </div>
                <% end %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          </div>
        <% else %>
          <img src="https://source.unsplash.com/random/?rocket" style="width: 100px; height: 100px;">
        <% end %>

        <div class="card-show-infos">
          <div>
            <h3>
              <i class="fa-solid fa-dollar-sign"></i>
              <%= @spaceship.price %>
              <span style="color: grey">per day</span>
            </h3>
          </div>
          <p class="card-show-category"><%= @spaceship.category %></p>
          <p>
            <% if @spaceship.user != current_user %>
            <% else %>
              <%= link_to edit_spaceship_path(@spaceship), class: "btn btn-success" do %>
                <%= content_tag(:i, "", class: "fa-solid fa-pencil-alt") %>
              <% end %>
            <% end %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-5">
      <div class="card-show mb-3">
        <p class="p-2">
              <i class="fa-solid fa-location-dot"></i>
              <%= @spaceship.location %>
        </p>
        <div style="width: 100%; height: 290px;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>

      <% if @spaceship.user != current_user %>
      <div class="card-show mb-5">
        <div class="container mt-6" >
          <div class="form-inputs">
            <%= simple_form_for [@spaceship, @booking], data: { controller: 'flatpickr' }, html: { class: "smth" } do |f| %>
                <div class="smoth"><%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %></div>
                <div class="smoth"><%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %></div>
              <div class="d-flex justify-content-between align-items-center mt-4">
                <div>
                  <%= render "shared/rocket_button" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<style>
.smth {
  display: inline-flex; justify-content: space-evenly; place-items: center;
}

.smoth {
  margin: 10px
}
</style>